version: '3.9'

services:
  postgres-listings:
    container_name: postgres-listings
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=listings-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres-listings:/var/lib/postgresql/data

  postgres-reservations:
    container_name: postgres-reservations
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=reservations-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres-reservations:/var/lib/postgresql/data

  postgres-users:
    container_name: postgres-users
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=users-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5434:5432"
    volumes:
      - ~/apps/postgres-users:/var/lib/postgresql/data

  ## Keycloak Config with Mysql database
  keycloak-mysql-airbnb:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  ## Keycloak Config
  keycloak-airbnb:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HOSTNAME: keycloak #By specifying this, http://keycloak:port can be accessed instead of localhost
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql-airbnb