version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=listing-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
