spring:
  application:
    name: users-service
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5434/users-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8383

# gRPC
grpc:
  server:
    port: 9393