spring:
  application:
    name: reservation-service
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5433/reservations-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 0

# Eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# gRPC
grpc:
  server:
    port: 9292